# Generated by Django 4.2.13 on 2024-08-01 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_couponusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='offer_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
