# Generated by Django 4.2.13 on 2024-07-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_offer_available', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default=0)),
                ('minimum_amount', models.IntegerField(default=100)),
                ('end_date', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['-id'],
            },
        ),
    ]
