# Generated by Django 4.2.13 on 2024-08-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
