# Generated by Django 4.2.13 on 2024-08-03 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Wallet',
            new_name='wallet',
        ),
    ]
