# Generated by Django 4.2.13 on 2024-08-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
    ]
