# Generated by Django 4.2.13 on 2024-08-08 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_referal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referal',
            old_name='amout',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='referal',
            old_name='referrer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='referal',
            name='reffered_user',
        ),
        migrations.AddField(
            model_name='referal',
            name='reffered_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
