# Generated by Django 4.2.13 on 2024-08-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_amout_referal_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='referal_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Referal',
        ),
    ]
