# Generated by Django 4.2.13 on 2024-08-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_address_referal_code_delete_referal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='referal_code',
            new_name='referral_code',
        ),
    ]
