# Generated by Django 4.2.13 on 2024-08-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_referal_code_address_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='referral_code',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
