# Generated by Django 4.2.13 on 2024-07-31 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('order', '0004_orderitem_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsize'),
        ),
    ]
