# Generated by Django 4.2.13 on 2024-07-31 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_orderitem_product_size'),
    ]

    operations = [
    ]
