# Generated by Django 4.2.13 on 2024-07-31 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('order', '0007_auto_20240731_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.productsize'),
        ),
    ]
