# Generated by Django 4.2.13 on 2024-08-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_order_status_orderitem_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discounted_amount',
            new_name='payable_amount',
        ),
    ]
