# Generated by Django 4.2.13 on 2024-08-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='paid_after_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
