# Generated by Django 4.2.13 on 2024-08-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_orderitem_paid_after_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='paid_after_discount',
            new_name='payment_after_discount',
        ),
    ]
