# Generated by Django 4.2.13 on 2024-08-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_rename_paid_after_discount_orderitem_payment_after_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
    ]
