# Generated by Django 4.2.13 on 2024-08-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('return_requested', 'Return Requested'), ('return_accepted', 'Return Accepted'), ('return_rejected', 'Return Rejected')], default='confirmed', max_length=20),
        ),
    ]
