# Generated by Django 4.2.13 on 2024-08-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_default_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='default_image',
        ),
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(null=True, upload_to='images/product'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_image2',
            field=models.ImageField(null=True, upload_to='images/product'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_image3',
            field=models.ImageField(null=True, upload_to='images/product'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_image4',
            field=models.ImageField(null=True, upload_to='images/product'),
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
