# Generated by Django 4.2.13 on 2024-08-09 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_products_default_image_products_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
