# Generated by Django 4.2.13 on 2024-08-09 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_max_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
