# Generated by Django 4.2.13 on 2024-08-09 13:54

from django.db import migrations,models
import django.core.validators



class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_products_max_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]